---
  apiVersion: v1
  kind: Pod
  metadata:
    name: uberany
    labels:
      name: uberany
  spec:
    containers:
      - image: eu.gcr.io/oval-method-115410/uberany
        name: uberany
        env:
          - name: giturl
            value: https://github.com/CIS-Tech-Futures/hello-world-node.git
          - name: username
            value: cistechfutures
          - name: password
            value: techfutu13
        ports:
          - containerPort: 80
            name: web
          - containerPort: 8080
            name: webalt
          - containerPort: 3000
            name: photon
