---
  kind: "Service"
  type: "LoadBalancer"
  apiVersion: "v1"
  metadata:
    name: "uberany"
    labels:
      app: "uberany"
  spec:
    ports:
      #Ports the service should serve on
      - port: 3000
        targetPort: 3000
      - port: 80
        targetPort: 80
      - port: 8080
        targetPort: 8080
    selector:
      app: "uberany"
